#pragma once


/*
 *
 * List of OOBD II Commands
 * 
 * Not a complete listing, just ones I care about
 */
enum ObdCommands
{
	//MODE 01
	FUEL_SYSTEM_STATUS, // PID 03
	CALCULATED_ENGINE_LOAD, // PID 04
	ENGINE_COOLANT_TEMPERATURE, // PID 05
	FUEL_PRESSURE, // PID 0A
	INTAKE_MANIFOLD_PRESSURE, // PID 0B
	ENGINE_RPM, // PID 0C
	VEHICLE_SPEED, // PID 0D,
	TIMING_ADVANCE, // PID 0E,
	INTAKE_AIR_TEMPERATURE, // PID 0F
	MAF, // PID 10,
	THROTTLE_POSITION, // PID 11
	ENGINE_RUN_TIME, // PI 1F
	FUEL_TAKE_LEVEL, // PID 2F
	AMBIENT_AIR_TEMPERATURE, // PID 46
	FUEL_TYPE, // PID 51
	ETHANOL_FUEL_PERCENTAGE, // PID 52
	ENGINE_OIL_TEMPERATURE, // PID 5C
	ENGINE_FUEL_RATE, // PID 5E
	TURBOCHARGER_RPM, // PID 74
	TURBOCHARGER_TEMPERATURE, // PID 75

	//MODE 09
	VIN, // PID 02
};