CREATE TABLE CAR_SUPPORTED_COMMANDS (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	CAR_ID BIGINT NOT NULL,
	PIDS_01_20_BITMASK INT NULL,
	PIDS_21_40_BITMASK INT NULL,
	PIDS_41_60_BITMASK INT NULL,
	PIDS_61_80_BITMASK INT NULL,
	PIDS_81_A0_BITMASK INT NULL,
	CREATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	MODIFIED_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (ID),
	FOREIGN KEY (CAR_ID) REFERENCES CAR(ID)
);