CREATE TABLE GPS_READING (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	LATITUDE DECIMAL(10, 7) NOT NULL,
	LOGITUDE DECIMAL(10, 7) NOT NULL,
	READ_DATE DATETIME NOT NULL,
	TRIP_ID BIGINT NOT NULL,
	CREATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	MODIFIED_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (ID),
	FOREIGN KEY (TRIP_ID) REFERENCES TRIP(ID)
);
