CREATE TABLE PLACE (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	GOOGLE_PLACE_ID VARCHAR(250) NULL,
	NAME VARCHAR(250) NOT NULL,
	
	LATITUDE DECIMAL(10, 7) NOT NULL,
	LONGITUDE DECIMAL(10, 7) NOT NULL,
	
	ACTIVE BIT NOT NULL DEFAULT 1,
	
	CREATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	MODIFIED_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (ID)
);


