CREATE TABLE READING (
	ID BIGINT NOT NULL AUTO_INCREMENT,	
	READ_DATE DATETIME NOT NULL,	
	TRIP_ID BIGINT NOT NULL,
	CREATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	MODIFIED_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (ID),
	FOREIGN KEY (TRIP_ID) REFERENCES TRIP(ID)
);
