CREATE TABLE TRIP (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	START_DATE DATETIME NOT NULL,
	END_DATE DATETIME NULL,
	NAME VARCHAR(250) NULL,
	CAR_ID BIGINT NOT NULL,
	AVERAGE_SPEED DOUBLE NULL,
	MAX_SPEED DOUBLE NULL,
	AVERAGE_ENGINE_RPM DOUBLE NULL,
	MAX_ENGINE_RPM DOUBLE NULL,
	DISTANCE_TRAVELED DOUBLE NULL,
	IDLE_TIME BIGINT NULL,
	STATUS VARCHAR(50) NOT NULL,
	CREATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	MODIFIED_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (ID),
	FOREIGN KEY (CAR_ID) REFERENCES CAR(ID),
	FOREIGN KEY (STATUS) REFERENCES TRIP_STATUS(ID)
);
