CREATE TABLE TRIP_POSSIBLE_PLACE (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	TRIP_ID BIGINT NOT NULL,
	PLACE_ID BIGINT NOT NULL,
	PLACE_TYPE VARCHAR(50) NOT NULL,	
	CREATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	MODIFIED_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (ID),
	FOREIGN KEY (TRIP_ID) REFERENCES TRIP(ID),
	FOREIGN KEY (PLACE_ID) REFERENCES PLACE(ID)
);
