CREATE TABLE TRIP_STATUS (
	ID VARCHAR(50) NOT NULL,
	DESCRIPTION VARCHAR(500) NOT NULL,
	CREATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	MODIFIED_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (ID)
);