CREATE TABLE USER_REGISTRATION_KEY_USE (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	KEY_ID BIGINT NOT NULL,
	USER_ID BIGINT NOT NULL,
	CREATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	MODIFIED_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (ID),
	FOREIGN KEY (KEY_ID) REFERENCES USER_REGISTRATION_KEY(ID),
	FOREIGN KEY (USER_ID) REFERENCES USER(ID)
);