CREATE TABLE USER_REGISTRATION_KEY (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	KEY_VAL VARCHAR(100) NOT NULL UNIQUE,
	USES_REMAINING INT NOT NULL,
	ACTIVE BIT NOT NULL DEFAULT 1,
	CREATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	MODIFIED_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (ID)
);