CREATE TABLE USER_AUTHENTICATION_TOKEN (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	USER_ID BIGINT NOT NULL,
	TOKEN VARCHAR(64) NOT NULL,
	DEVICE_UUID VARCHAR(250) NOT NULL,
	ACTIVE BIT NOT NULL DEFAULT 0,
	LAST_LOGIN DATETIME NULL,
	LAST_LOGIN_ADDRESS VARCHAR(250) NULL,
	EXPIRATION_DATE DATETIME NULL,
	CREATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	MODIFIED_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT UAT_PK PRIMARY KEY (ID),
	CONSTRAINT UAT_USER_ID FOREIGN KEY (USER_ID) REFERENCES USER(ID),
	CONSTRAINT UAT_TOKEN_UNIQUE UNIQUE (TOKEN)
);