package com.ricex.cartracker.common.enums;

/** Listing of the Majority of the OBII Commands
 * 
 * Some of the commands are duplicated across different PIDS
 * 
 * @author Mitchell
 *
 */

public enum ObdCommand {

	MONITOR_STATUS,
	FREEZE_DTC,
	FUEL_SYSTEM_STATUS,
	CALCULATED_ENGINE_LOAD,
	ENGINE_COOLANT_TEMPERATURE,
	SHORT_TERM_FUEL_TRIM_BANK_1,
	LONG_TERM_FUEL_TRIM_BANK_1,
	SHORT_TERM_FUEL_TRIM_BANK_2,
	LONG_TERM_FUEL_TRIM_BANK_2,
	FUEL_PRESSURE,
	INTAKE_MANIFOLD_ABSOLUTE_PRESSURE,
	ENGINE_RPM,
	VEHICLE_SPEED,
	TIMING_ADVANCE,
	INTAKE_AIR_TEMPERATURE,
	MAF,
	THROTTLE_POSITION,
	COMMANDED_SECONDARY_AIR_STATUS,
	OXYGEN_SENSORS_PRESENT_BANKS_2,
	OXYGEN_SENSOR_1,
	OXYGEN_SENSOR_2,
	OXYGEN_SENSOR_3,
	OXYGEN_SENSOR_4,
	OXYGEN_SENSOR_5,
	OXYGEN_SENSOR_6,
	OXYGEN_SENSOR_7,
	OXYGEN_SENSOR_8,
	OBD_STANDARDS,
	OXYGEN_SENSORS_PRESENT_BANKS_4,
	AUXILIARY_INPUT_STATUS,
	RUN_TIME_SINCE_ENGINE_START,
	DISTANCE_TRAVELED_WITH_MIL_ON,
	FUEL_RAIL_PRESSURE,
	FUEL_RAIL_GAUGE_PRESSURE,
	//More Oxygen Sensors?
	COMMANDED_EGR,
	EGR_ERROR,
	COMMANDED_EVAPORATE_PURGE,
	FUEL_TANK_LEVEL_INPUT,
	WARM_UPS_SINCE_CODES_CLEARED,
	DISTANCE_TRAVELED_SINCE_CODES_CLEARED,
	EVAP_SYSTEM_VAPOR_PRESSURE,
	ABSOLUTE_BAROMETRIC_PRESSURE,
	//More Oxygen Sensors?
	CATALYST_TEMPERATURE_BANK_1_SENSOR_1,
	CATALYST_TEMPERATURE_BANK_2_SENSOR_1,
	CATALYST_TEMPERATURE_BANK_1_SENSOR_2,
	CATALYST_TEMPERATURE_BANK_2_SENSOR_2,
	MONITOR_STATUS_THIS_DRIVE_CYCLE,
	CONTROL_MODULE_VOLTAGE,
	ABSOLUTE_LOAD_VALUE,
	FUEL_AIR_COMMANDED_EQUIVALENCE_RATIO,
	RELATIVE_THROTTLE_POSITION,
	AMBIENT_AIR_TEMPERATURE,
	ABSOLUTE_THROTTLE_POSITION_B,
	ABSOLUTE_THROTTLE_POSITION_C,
	ACCELERATOR_PEDAL_POSITION_D,
	ACCELERATOR_PEDAL_POSITION_E,
	ACCELERATOR_PEDAL_POSITION_F,
	COMMANDED_THROTTLE_ACTUATOR,
	TIME_RUN_WITH_MIL_ON,
	TIME_SINCE_TROUBLE_CODES_CLEARED,
	MAX_FUEL_AIR_EQUIVALENCE_RATIO,
	MAX_MAF,
	FUEL_TYPE,
	ETHANOL_FUEL_PERCENT,
	ABSOLUTE_EVAP_SYSTEM_VAPOR_PRESSURE,
	//EVAP_SYSTEM_VAPOR_PRESSURE, // duplicated from earlier PID
	//More oxygen sensors
	FUEL_RAIL_ABSOLUTE_PRESSURE,
	RELATIVE_ACCELERATOR_PEDAL_POSITION,
	HYBRID_BATTERY_PACK_REMAINING_LIFE,
	ENGINE_OIL_TEMPERATURE,
	FUEL_INJECTION_TIMING,
	ENGINE_FUEL_RATE,
	EMISSIONS_REQUIREMENTS_STANDARDS,
	DRIVERS_DEMAND_ENGINE_TORQUE_PERCENT,
	ACTUAL_ENGINE_TORQUE_PERCENT,
	ENGINE_REFERENCE_TORQUE,
	ENGINE_TORQUE_PERCENT,
//	ENGINE_COOLANT_TEMPERATURE, // Duplicated?
	EXHAUST_GAS_RECIRCULATION_TEMPERATURE,
	TURBOCHARGER_COMPRESSOR_INLET_PRESSURE,
	BOOST_PRESSURE_CONTROL,
	WASTEGATE_CONTROL,
	EXHAUST_PRESSURE,
	TURBOCHARGER_RPM,
	TURBOCHARGER_TEMPERATURE_1,
	TURBOCHARGER_TEMPERATURE_2,
	CHARGE_AIR_COOLER_TEMPERATURE,
	EXHAUST_GAS_TEMPERATURE_BANK_1,
	EXHAUST_GAS_TEMPERATURE_BANK_2,
	ENGINE_RUN_TIME
	
	;	
	
}
